import * as fs from 'node:fs/promises'
import * as path from 'node:path'

/** Header text used to identify installer files managed by Incur. */
export const marker = 'Generated by Incur. Do not edit.'

/** Renders pinned install scripts for an Incur standalone-binary release. */
export function generate(options: generate.Options): generate.Result {
  const release = normalize(options)
  return {
    powershell: renderPowershell(release),
    shell: renderShell(release),
  }
}

export declare namespace generate {
  /** Installer release metadata. */
  type Options = {
    /** Standalone executable name. */
    name: string
    /** Public GitHub repository in `owner/name` form. */
    repository: string
    /** Exact GitHub release tag containing the binary assets. */
    tag: string
    /** Exact stable version reported by the installed executable. */
    version: string
  }

  /** Rendered installer scripts. */
  type Result = {
    /** Windows PowerShell installer contents. */
    powershell: string
    /** POSIX shell installer contents. */
    shell: string
  }
}

/** Writes pinned install scripts into a release asset directory. */
export async function write(options: write.Options): Promise<write.Result> {
  const output = path.resolve(options.output)
  const scripts = generate(options)
  const powershell = path.join(output, 'install.ps1')
  const shell = path.join(output, 'install.sh')
  await fs.mkdir(output, { recursive: true })
  await Promise.all([
    fs.writeFile(powershell, scripts.powershell),
    fs.writeFile(shell, scripts.shell, { mode: 0o755 }),
  ])
  await fs.chmod(shell, 0o755)
  return {
    ...scripts,
    powershellPath: powershell,
    shellPath: shell,
  }
}

export declare namespace write {
  /** Installer file generation options. */
  type Options = generate.Options & {
    /** Directory that receives `install.sh` and `install.ps1`. */
    output: string
  }

  /** Written installer scripts and their absolute paths. */
  type Result = generate.Result & {
    /** Absolute path to `install.ps1`. */
    powershellPath: string
    /** Absolute path to `install.sh`. */
    shellPath: string
  }
}

type Release = {
  installVariable: string
  name: string
  repository: string
  tag: string
  version: string
}

function normalize(options: generate.Options): Release {
  const name = options.name.trim()
  const repository = options.repository.trim()
  const tag = options.tag.trim()
  const version = options.version.trim()

  if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(name))
    throw new Error(`Invalid CLI name: ${options.name}`)
  if (isWindowsReserved(name)) throw new Error(`Invalid cross-platform CLI name: ${options.name}`)
  if (!isRepository(repository))
    throw new Error(`Invalid GitHub repository '${options.repository}'. Expected 'owner/name'.`)
  if (!/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(version))
    throw new Error(`Invalid stable version: ${options.version}`)
  if (stableVersion(tag) !== version)
    throw new Error(`Release tag '${options.tag}' does not identify version ${version}.`)

  const installVariable = `${name.toUpperCase().replaceAll(/[^A-Z0-9]/g, '_')}_INSTALL_DIR`
  return {
    installVariable: /^\d/.test(installVariable) ? `_${installVariable}` : installVariable,
    name,
    repository,
    tag,
    version,
  }
}

function stableVersion(tag: string): string | undefined {
  const match = tag.match(
    /^(?:[vV]?|(?:@[A-Za-z0-9][A-Za-z0-9._~-]*\/)?[A-Za-z0-9][A-Za-z0-9._~-]*@)(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/,
  )
  if (!match) return undefined
  return `${match[1]}.${match[2]}.${match[3]}`
}

function isRepository(repository: string): boolean {
  const [owner, name, extra] = repository.split('/')
  if (!owner || !name || extra) return false
  if (owner === '.' || owner === '..' || name === '.' || name === '..') return false
  return /^[A-Za-z0-9_.-]+$/.test(owner) && /^[A-Za-z0-9_.-]+$/.test(name)
}

function isWindowsReserved(name: string): boolean {
  if (name.endsWith('.')) return true
  const stem = name.split('.')[0]!.toUpperCase()
  return /^(AUX|CON|NUL|PRN|COM[1-9]|LPT[1-9])$/.test(stem)
}

function renderShell(release: Release): string {
  const { installVariable, name, repository, tag, version } = release
  return (
    [
      '#!/bin/sh',
      `# ${marker}`,
      'set -eu',
      '',
      `name='${name}'`,
      `version='${version}'`,
      `tag='${tag}'`,
      `repository='${repository}'`,
      'base_url="https://github.com/$repository/releases/download/$tag"',
      '',
      'fail() {',
      '  printf \'%s\\n\' "error: $*" >&2',
      '  exit 1',
      '}',
      '',
      'for command in awk curl gzip mktemp uname; do',
      '  command -v "$command" >/dev/null 2>&1 || fail "required command not found: $command"',
      'done',
      '',
      'detect_libc() {',
      '  if command -v ldd >/dev/null 2>&1; then',
      '    ldd_output=$(ldd --version 2>&1 || true)',
      '    case "$ldd_output" in',
      "      *musl*) printf '%s\\n' musl; return ;;",
      '      *GLIBC*|*glibc*|*GNU*|*"Free Software Foundation"*) printf \'%s\\n\' glibc; return ;;',
      '    esac',
      '  fi',
      '',
      '  if command -v getconf >/dev/null 2>&1; then',
      '    getconf_output=$(getconf GNU_LIBC_VERSION 2>/dev/null || true)',
      '    case "$getconf_output" in',
      "      glibc*) printf '%s\\n' glibc; return ;;",
      '    esac',
      '  fi',
      '',
      '  for loader in /lib/ld-musl-*.so.1 /usr/lib/ld-musl-*.so.1; do',
      '    if [ -e "$loader" ]; then',
      "      printf '%s\\n' musl",
      '      return',
      '    fi',
      '  done',
      '',
      '  fail "could not determine whether this Linux system uses glibc or musl"',
      '}',
      '',
      'system=$(uname -s)',
      'machine=$(uname -m)',
      'case "$machine" in',
      '  arm64|aarch64) architecture=arm64 ;;',
      '  x86_64|amd64) architecture=x64 ;;',
      '  *) fail "unsupported architecture: $machine" ;;',
      'esac',
      '',
      'case "$system" in',
      '  Darwin)',
      '    target="darwin-$architecture"',
      '    ;;',
      '  Linux)',
      '    libc=$(detect_libc)',
      '    if [ "$architecture" = x64 ]; then',
      '      target="linux-x64-$libc-baseline"',
      '    else',
      '      target="linux-arm64-$libc"',
      '    fi',
      '    ;;',
      '  *) fail "unsupported operating system: $system" ;;',
      'esac',
      '',
      'asset="$name-$target.gz"',
      `install_dir="\${${installVariable}:-\${INSTALL_DIR:-}}"`,
      'if [ -z "$install_dir" ]; then',
      '  [ -n "${HOME:-}" ] || fail "HOME is unset; set INSTALL_DIR explicitly"',
      '  install_dir="$HOME/.local/bin"',
      'fi',
      '',
      'temporary=$(mktemp -d "${TMPDIR:-/tmp}/$name-install.XXXXXX")',
      "staged=''",
      'cleanup() {',
      '  rm -rf "$temporary"',
      '  if [ -n "$staged" ]; then rm -f "$staged"; fi',
      '}',
      'trap cleanup 0',
      "trap 'exit 1' HUP INT TERM",
      '',
      'archive="$temporary/$asset"',
      'checksums="$temporary/SHA256SUMS"',
      'candidate="$temporary/$name"',
      "curl --proto '=https' --tlsv1.2 --fail --silent --show-error --location \\",
      '  --output "$archive" "$base_url/$asset"',
      "curl --proto '=https' --tlsv1.2 --fail --silent --show-error --location \\",
      '  --output "$checksums" "$base_url/SHA256SUMS"',
      '',
      'expected=$(',
      '  awk -v asset="$asset" \'',
      '    $2 == asset && $1 ~ /^[0-9A-Fa-f]+$/ && length($1) == 64 {',
      '      digest = $1',
      '      matches++',
      '    }',
      '    END {',
      '      if (matches != 1) exit 1',
      '      print digest',
      '    }',
      '  \' "$checksums"',
      ') || fail "SHA256SUMS does not contain exactly one checksum for $asset"',
      '',
      'if command -v sha256sum >/dev/null 2>&1; then',
      '  actual=$(sha256sum "$archive" | awk \'{ print $1 }\')',
      'elif command -v shasum >/dev/null 2>&1; then',
      '  actual=$(shasum -a 256 "$archive" | awk \'{ print $1 }\')',
      'else',
      '  fail "SHA-256 verification requires sha256sum or shasum"',
      'fi',
      '[ "$actual" = "$expected" ] || fail "SHA-256 checksum mismatch for $asset"',
      '',
      'gzip -dc "$archive" > "$candidate"',
      'chmod 755 "$candidate"',
      'actual_version=$("$candidate" --version) || fail "downloaded binary failed version validation"',
      '[ "$actual_version" = "$version" ] || \\',
      '  fail "downloaded binary reported version $actual_version, expected $version"',
      '',
      'mkdir -p "$install_dir"',
      'destination="$install_dir/$name"',
      '[ ! -d "$destination" ] || fail "install destination is a directory: $destination"',
      'staged=$(mktemp "$install_dir/.$name-install.XXXXXX")',
      'cp "$candidate" "$staged"',
      'chmod 755 "$staged"',
      'mv -f "$staged" "$destination"',
      "staged=''",
      '',
      'printf \'Installed %s %s to %s\\n\' "$name" "$version" "$destination"',
      'case ":${PATH:-}:" in',
      '  *:"$install_dir":*) ;;',
      '  *) printf \'Add %s to PATH to run %s.\\n\' "$install_dir" "$name" ;;',
      'esac',
    ].join('\n') + '\n'
  )
}

function renderPowershell(release: Release): string {
  const { installVariable, name, repository, tag, version } = release
  return (
    [
      `# ${marker}`,
      "$ErrorActionPreference = 'Stop'",
      "$ProgressPreference = 'SilentlyContinue'",
      'Set-StrictMode -Version Latest',
      '',
      `$name = '${name}'`,
      `$version = '${version}'`,
      `$tag = '${tag}'`,
      `$repository = '${repository}'`,
      '$baseUrl = "https://github.com/$repository/releases/download/$tag"',
      '',
      "if ($env:OS -ne 'Windows_NT') {",
      "  throw 'This installer supports Windows only.'",
      '}',
      '',
      '$architecture = [Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()',
      'switch ($architecture) {',
      "  'Arm64' { $target = 'windows-arm64' }",
      "  'X64' { $target = 'windows-x64-baseline' }",
      '  default { throw "Unsupported architecture: $architecture" }',
      '}',
      '',
      '$asset = "$name-$target.exe.gz"',
      `$installDir = [Environment]::GetEnvironmentVariable('${installVariable}')`,
      'if (-not $installDir) { $installDir = $env:INSTALL_DIR }',
      "if (-not $installDir) { $installDir = Join-Path $HOME '.local\\bin' }",
      '$installDir = [IO.Path]::GetFullPath($installDir)',
      '',
      "if (-not (Get-Command -Name 'Get-FileHash' -ErrorAction SilentlyContinue)) {",
      "  throw 'SHA-256 verification requires Get-FileHash.'",
      '}',
      '[Net.ServicePointManager]::SecurityProtocol =',
      '  [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12',
      '',
      '$temporary = Join-Path ([IO.Path]::GetTempPath()) ("$name-install-" + [Guid]::NewGuid().ToString(\'N\'))',
      '$staged = $null',
      'New-Item -ItemType Directory -Path $temporary | Out-Null',
      '',
      'try {',
      '  $archive = Join-Path $temporary $asset',
      "  $checksumFile = Join-Path $temporary 'SHA256SUMS'",
      '  $candidate = Join-Path $temporary "$name.exe"',
      '  Invoke-WebRequest -UseBasicParsing -Uri "$baseUrl/$asset" -OutFile $archive',
      '  Invoke-WebRequest -UseBasicParsing -Uri "$baseUrl/SHA256SUMS" -OutFile $checksumFile',
      '',
      '  $checksumContents = [IO.File]::ReadAllText($checksumFile)',
      '  $pattern = \'(?m)^([0-9A-Fa-f]{64})  \' + [Regex]::Escape($asset) + "\\r?$"',
      '  $checksumMatches = [Regex]::Matches($checksumContents, $pattern)',
      '  if ($checksumMatches.Count -ne 1) {',
      '    throw "SHA256SUMS does not contain exactly one checksum for $asset."',
      '  }',
      '  $expected = $checksumMatches[0].Groups[1].Value',
      "  $actual = (Get-FileHash -LiteralPath $archive -Algorithm 'SHA256').Hash",
      '  if (-not [string]::Equals($actual, $expected, [StringComparison]::OrdinalIgnoreCase)) {',
      '    throw "SHA-256 checksum mismatch for $asset."',
      '  }',
      '',
      '  $source = [IO.File]::OpenRead($archive)',
      '  try {',
      '    $gzip = [IO.Compression.GzipStream]::new(',
      '      $source,',
      '      [IO.Compression.CompressionMode]::Decompress',
      '    )',
      '    try {',
      '      $output = [IO.File]::Create($candidate)',
      '      try {',
      '        $gzip.CopyTo($output)',
      '      } finally {',
      '        $output.Dispose()',
      '      }',
      '    } finally {',
      '      $gzip.Dispose()',
      '    }',
      '  } finally {',
      '    $source.Dispose()',
      '  }',
      '',
      "  $versionOutput = @(& $candidate '--version' 2>&1)",
      '  if ($LASTEXITCODE -ne 0) {',
      '    throw "Downloaded binary failed version validation with exit code $LASTEXITCODE."',
      '  }',
      '  $actualVersion = ($versionOutput -join [Environment]::NewLine).Trim()',
      '  if ($actualVersion -ne $version) {',
      '    throw "Downloaded binary reported version $actualVersion, expected $version."',
      '  }',
      '',
      '  New-Item -ItemType Directory -Path $installDir -Force | Out-Null',
      '  $destination = Join-Path $installDir "$name.exe"',
      '  if ([IO.Directory]::Exists($destination)) {',
      '    throw "Install destination is a directory: $destination"',
      '  }',
      "  $staged = Join-Path $installDir (\".$name-install-\" + [Guid]::NewGuid().ToString('N') + '.exe')",
      '  [IO.File]::Copy($candidate, $staged, $false)',
      '  if ([IO.File]::Exists($destination)) {',
      '    [IO.File]::Replace($staged, $destination, $null, $true)',
      '  } else {',
      '    [IO.File]::Move($staged, $destination)',
      '  }',
      '  $staged = $null',
      '',
      '  Write-Host "Installed $name $version to $destination"',
      "  if (($env:PATH -split ';') -notcontains $installDir) {",
      '    Write-Host "Add $installDir to PATH to run $name."',
      '  }',
      '} finally {',
      '  if ($staged -and [IO.File]::Exists($staged)) {',
      '    Remove-Item -LiteralPath $staged -Force -ErrorAction SilentlyContinue',
      '  }',
      '  if ([IO.Directory]::Exists($temporary)) {',
      '    Remove-Item -LiteralPath $temporary -Recurse -Force -ErrorAction SilentlyContinue',
      '  }',
      '}',
    ].join('\n') + '\n'
  )
}
