import { execFile } from 'node:child_process'
import { createHash } from 'node:crypto'
import { chmod, mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { promisify } from 'node:util'
import { gzipSync } from 'node:zlib'

import { generate, write as writeInstallers } from './binaryInstaller.js'

const exec = promisify(execFile)

let directory: string

beforeEach(async () => {
  directory = await mkdtemp(join(tmpdir(), 'incur-binary-installer-'))
})

afterEach(async () => {
  await rm(directory, { force: true, recursive: true })
})

describe('generate', () => {
  test('renders pinned shell and PowerShell installers for the canonical assets', () => {
    const result = generate({
      name: 'frog-cli',
      repository: 'wevm/frog',
      tag: 'v1.2.3',
      version: '1.2.3',
    })

    expect({
      powershellConstants: result.powershell
        .split('\n')
        .filter((line) => /^\$(name|repository|tag|version) =/.test(line)),
      powershellSafety: [
        result.powershell.includes('Get-FileHash'),
        result.powershell.includes('[IO.File]::Replace($staged, $destination, $null, $true)'),
        result.powershell.includes("$versionOutput = @(& $candidate '--version' 2>&1)"),
      ],
      shellConstants: result.shell
        .split('\n')
        .filter((line) => /^(name|repository|tag|version)=/.test(line)),
      shellSafety: [
        result.shell.includes('SHA-256 verification requires sha256sum or shasum'),
        result.shell.includes('actual_version=$("$candidate" --version)'),
        result.shell.includes('mv -f "$staged" "$destination"'),
      ],
    }).toMatchInlineSnapshot(`
      {
        "powershellConstants": [
          "$name = 'frog-cli'",
          "$version = '1.2.3'",
          "$tag = 'v1.2.3'",
          "$repository = 'wevm/frog'",
        ],
        "powershellSafety": [
          true,
          true,
          true,
        ],
        "shellConstants": [
          "name='frog-cli'",
          "version='1.2.3'",
          "tag='v1.2.3'",
          "repository='wevm/frog'",
        ],
        "shellSafety": [
          true,
          true,
          true,
        ],
      }
    `)
    expect(result.shell).toContain('install_dir="${FROG_CLI_INSTALL_DIR:-${INSTALL_DIR:-}}"')
    expect(result.shell).toContain(
      '[ ! -d "$destination" ] || fail "install destination is a directory: $destination"',
    )
    expect(result.shell).toMatch(/^#!\/bin\/sh\n# Generated by Incur\. Do not edit\./)
    expect(result.powershell).toMatch(/^# Generated by Incur\. Do not edit\./)
    expect(result.shell).toContain('target="linux-x64-$libc-baseline"')
    expect(result.shell).toContain('target="linux-arm64-$libc"')
    expect(result.powershell).toContain("'Arm64' { $target = 'windows-arm64' }")
    expect(result.powershell).toContain("'X64' { $target = 'windows-x64-baseline' }")
    expect(result.powershell).toContain('throw "Install destination is a directory: $destination"')
  })

  test('rejects metadata that cannot be embedded safely or consistently', () => {
    const options = {
      name: 'frog',
      repository: 'wevm/frog',
      tag: 'v1.2.3',
      version: '1.2.3',
    }

    expect(() => generate({ ...options, name: '../frog' })).toThrow('Invalid CLI name')
    expect(() => generate({ ...options, name: 'con' })).toThrow('Invalid cross-platform CLI name')
    expect(() => generate({ ...options, name: 'aux.log' })).toThrow(
      'Invalid cross-platform CLI name',
    )
    expect(() => generate({ ...options, name: 'frog.' })).toThrow('Invalid cross-platform CLI name')
    expect(() => generate({ ...options, repository: 'wevm/frog/other' })).toThrow(
      "Invalid GitHub repository 'wevm/frog/other'",
    )
    expect(() => generate({ ...options, version: '1.2.3-beta.1' })).toThrow(
      'Invalid stable version',
    )
    expect(() => generate({ ...options, tag: 'v1.2.4' })).toThrow(
      "Release tag 'v1.2.4' does not identify version 1.2.3.",
    )
    expect(() => generate({ ...options, tag: "frog'@1.2.3" })).toThrow(
      "Release tag 'frog'@1.2.3' does not identify version 1.2.3.",
    )
    expect(generate({ ...options, tag: '@example/frog@1.2.3' }).shell).toContain(
      "tag='@example/frog@1.2.3'",
    )
    expect(generate({ ...options, name: '7zip' }).shell).toContain(
      'install_dir="${_7ZIP_INSTALL_DIR:-${INSTALL_DIR:-}}"',
    )
  })

  test('detects Darwin, glibc Linux, and musl Linux assets before installing', async () => {
    const fixtures = await createFixtures()
    const script = join(directory, 'install.sh')
    await writeFile(
      script,
      generate({
        name: 'frog',
        repository: 'wevm/frog',
        tag: 'v1.2.3',
        version: '1.2.3',
      }).shell,
      { mode: 0o755 },
    )

    const cases = [
      {
        asset: 'frog-darwin-arm64.gz',
        libc: 'unknown',
        machine: 'arm64',
        system: 'Darwin',
      },
      {
        asset: 'frog-linux-x64-glibc-baseline.gz',
        libc: 'glibc',
        machine: 'x86_64',
        system: 'Linux',
      },
      {
        asset: 'frog-linux-arm64-musl.gz',
        libc: 'musl',
        machine: 'aarch64',
        system: 'Linux',
      },
    ]

    for (const [index, value] of cases.entries()) {
      const install = join(directory, `install-${index}`)
      const release = join(directory, `release-${index}`)
      const requests = join(directory, `requests-${index}.txt`)
      await mkdir(release)
      await writeRelease(release, value.asset, '1.2.3')

      const { stdout } = await exec('sh', [script], {
        env: {
          ...process.env,
          FIXTURE_DIR: release,
          INSTALL_DIR: install,
          PATH: `${fixtures}:${process.env.PATH}`,
          REQUEST_LOG: requests,
          TEST_LIBC: value.libc,
          TEST_MACHINE: value.machine,
          TEST_SYSTEM: value.system,
        },
      })

      expect(stdout).toContain(`Installed frog 1.2.3 to ${join(install, 'frog')}`)
      await expect(exec(join(install, 'frog'), ['--version'])).resolves.toMatchObject({
        stdout: '1.2.3\n',
      })
      await expect(readFile(requests, 'utf8')).resolves.toBe(
        [
          `https://github.com/wevm/frog/releases/download/v1.2.3/${value.asset}`,
          'https://github.com/wevm/frog/releases/download/v1.2.3/SHA256SUMS',
          '',
        ].join('\n'),
      )
    }
  }, 15_000)

  test('preserves an existing installation when checksum verification fails', async () => {
    const fixtures = await createFixtures()
    const release = join(directory, 'release')
    const install = join(directory, 'bin')
    const installed = join(install, 'frog')
    await Promise.all([mkdir(release), mkdir(install)])
    await writeRelease(release, 'frog-linux-x64-musl-baseline.gz', '1.2.3')
    await writeFile(
      join(release, 'SHA256SUMS'),
      `${'0'.repeat(64)}  frog-linux-x64-musl-baseline.gz\n`,
    )
    await writeExecutable(installed, '0.9.0')

    const script = join(directory, 'install.sh')
    await writeFile(
      script,
      generate({
        name: 'frog',
        repository: 'wevm/frog',
        tag: 'v1.2.3',
        version: '1.2.3',
      }).shell,
      { mode: 0o755 },
    )

    await expect(
      exec('sh', [script], {
        env: {
          ...process.env,
          FIXTURE_DIR: release,
          INSTALL_DIR: install,
          PATH: `${fixtures}:${process.env.PATH}`,
          REQUEST_LOG: join(directory, 'requests.txt'),
          TEST_LIBC: 'musl',
          TEST_MACHINE: 'x86_64',
          TEST_SYSTEM: 'Linux',
        },
      }),
    ).rejects.toThrow('SHA-256 checksum mismatch')
    await expect(exec(installed, ['--version'])).resolves.toMatchObject({
      stdout: '0.9.0\n',
    })
  })

  test('rejects a directory at the install destination', async () => {
    const fixtures = await createFixtures()
    const release = join(directory, 'release')
    const install = join(directory, 'bin')
    await Promise.all([mkdir(release), mkdir(join(install, 'frog'), { recursive: true })])
    await writeRelease(release, 'frog-linux-x64-glibc-baseline.gz', '1.2.3')

    const script = join(directory, 'install.sh')
    await writeFile(
      script,
      generate({
        name: 'frog',
        repository: 'wevm/frog',
        tag: 'v1.2.3',
        version: '1.2.3',
      }).shell,
      { mode: 0o755 },
    )

    await expect(
      exec('sh', [script], {
        env: {
          ...process.env,
          FIXTURE_DIR: release,
          INSTALL_DIR: install,
          PATH: `${fixtures}:${process.env.PATH}`,
          REQUEST_LOG: join(directory, 'requests.txt'),
          TEST_LIBC: 'glibc',
          TEST_MACHINE: 'x86_64',
          TEST_SYSTEM: 'Linux',
        },
      }),
    ).rejects.toThrow('install destination is a directory')
    expect((await stat(join(install, 'frog'))).isDirectory()).toBe(true)
  })
})

describe('write', () => {
  test('writes standard installer filenames and marks the shell script executable', async () => {
    const output = join(directory, 'release')
    const result = await writeInstallers({
      name: 'frog',
      output,
      repository: 'wevm/frog',
      tag: '1.2.3',
      version: '1.2.3',
    })

    expect(result).toMatchObject({
      powershellPath: join(output, 'install.ps1'),
      shellPath: join(output, 'install.sh'),
    })
    await expect(readFile(result.powershellPath, 'utf8')).resolves.toBe(result.powershell)
    await expect(readFile(result.shellPath, 'utf8')).resolves.toBe(result.shell)
    expect((await stat(result.shellPath)).mode & 0o111).not.toBe(0)
  })
})

async function createFixtures(): Promise<string> {
  const commands = join(directory, 'commands')
  await mkdir(commands)
  await writeFile(
    join(commands, 'curl'),
    `#!/bin/sh
output=''
url=''
while [ "$#" -gt 0 ]; do
  case "$1" in
    --output) output=$2; shift 2 ;;
    http*) url=$1; shift ;;
    *) shift ;;
  esac
done
printf '%s\\n' "$url" >> "$REQUEST_LOG"
cp "$FIXTURE_DIR/\${url##*/}" "$output"
`,
  )
  await writeFile(
    join(commands, 'uname'),
    `#!/bin/sh
if [ "\${1:-}" = '-s' ]; then
  printf '%s\\n' "$TEST_SYSTEM"
else
  printf '%s\\n' "$TEST_MACHINE"
fi
`,
  )
  await writeFile(
    join(commands, 'ldd'),
    `#!/bin/sh
case "$TEST_LIBC" in
  glibc) printf '%s\\n' 'ldd (GNU libc)' ;;
  musl) printf '%s\\n' 'musl libc'; exit 1 ;;
  *) exit 1 ;;
esac
`,
  )
  await Promise.all(['curl', 'ldd', 'uname'].map((file) => chmod(join(commands, file), 0o755)))
  return commands
}

async function writeRelease(directory: string, asset: string, version: string): Promise<void> {
  const executable = `#!/bin/sh
if [ "\${1:-}" = '--version' ]; then
  printf '%s\\n' '${version}'
  exit 0
fi
exit 1
`
  const archive = gzipSync(executable)
  const digest = createHash('sha256').update(archive).digest('hex')
  await Promise.all([
    writeFile(join(directory, asset), archive),
    writeFile(join(directory, 'SHA256SUMS'), `${digest}  ${asset}\n`),
  ])
}

async function writeExecutable(file: string, version: string): Promise<void> {
  await writeFile(
    file,
    `#!/bin/sh
printf '%s\\n' '${version}'
`,
    { mode: 0o755 },
  )
}
