name: Verify
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: verify-${{ github.ref_type }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check code
        run: pnpm check

      - name: Check types
        run: pnpm check:types

  test:
    name: Test Runtime
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run tests
        run: pnpm run test --bail=1 --coverage
        env:
          CI: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
